# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14bcfa035d4e01bb8b8441e79d9d61ea79f0b30ff3165a59234ff4fea0b25532fe6cd1013912c29ab6d46250a8f1570818d60aebc54e1a89735cfc204f4272b8

test:
  secret_key_base: df3c7b835392c9562ad8a3b4fd4d9f45b84bc35af9edc3d43fe223a6fab9251d1c4b32f7efd0a2c49abd55d248f0fb04d724073ad278ec456daf49552e193df2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
